# Generated by Django 6.1.1 on 2026-09-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaactividad',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Actividad de Auditoría', 'verbose_name_plural': 'Actividades de Auditoría'},
        ),
    ]
