# Generated by Django 6.1.1 on 2026-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='historiallaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Historial Laboral', 'verbose_name_plural': 'Historiales Laborales'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AddField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
